site_name: OmegaPrint
theme:
  name: readthedocs
  plugins:
    - search
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
nav:
  - 'index.md'
  - 'quickstart.md'
  - 'maintenance.md'
  - 'slicer.md'
  - 'support.md'
  - 'quality.md'
  - 'faq.md'
markdown_extensions:
  - attr_list
  - md_in_html